# Generated by Django 3.1.5 on 2021-01-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleAcad', '0003_auto_20210129_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(unique=True),
        ),
    ]
