# Generated by Django 3.1.5 on 2021-01-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleAcad', '0004_auto_20210129_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='numero_licenca',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='sala',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
