# Generated by Django 3.1.5 on 2021-01-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleAcad', '0006_auto_20210131_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.DecimalField(choices=[(0, '0.0'), (0.5, '0.5'), (1, '1.0'), (1.5, '1.5'), (2, '2.0'), (2.5, '2.5'), (3, '3.0'), (3.5, '3.5'), (4, '4.0'), (4.5, '4.5'), (5, '5.0'), (5.5, '5.5'), (6, '6.0'), (6.5, '6.5'), (7, '7.0'), (7.5, '7.5'), (8, '8.0'), (8.5, '8.5'), (9, '9.0'), (9.5, '9.5'), (10, '10.0')], decimal_places=1, max_digits=3),
        ),
    ]
